//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_2_3_1_1 {
            get {
                object obj = ResourceManager.GetObject("4-2-3-1-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;div id=&quot;wg-api-football-standings&quot;
        ///    data-host=&quot;v3.football.api-sports.io&quot;
        ///    data-key=&quot;6382ac6ee050e80202c6e4eb4ac42321&quot;
        ///    data-league=&quot;78&quot;
        ///    data-team=&quot;&quot;
        ///    data-season=&quot;2021&quot;
        ///    data-theme=&quot;dark&quot;
        ///    data-show-errors=&quot;true&quot;
        ///    data-show-logos=&quot;true&quot;
        ///    class=&quot;wg_loader&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;script
        ///    type=&quot;module&quot;
        ///    src=&quot;https://widgets.api-sports.io/football/1.1.8/widget.js&quot;&gt;
        ///&lt;/script&gt;
        ///
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string BuliStandings {
            get {
                return ResourceManager.GetString("BuliStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;div id=&quot;wg-api-football-standings&quot;
        ///    data-host=&quot;v3.football.api-sports.io&quot;
        ///    data-key=&quot;6382ac6ee050e80202c6e4eb4ac42321&quot;
        ///    data-league=&quot;88&quot;
        ///    data-team=&quot;&quot;
        ///    data-season=&quot;2021&quot;
        ///    data-theme=&quot;dark&quot;
        ///    data-show-errors=&quot;true&quot;
        ///    data-show-logos=&quot;true&quot;
        ///    class=&quot;wg_loader&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;script
        ///    type=&quot;module&quot;
        ///    src=&quot;https://widgets.api-sports.io/football/1.1.8/widget.js&quot;&gt;
        ///&lt;/script&gt;
        ///
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string EredeviseStandings {
            get {
                return ResourceManager.GetString("EredeviseStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;div id=&quot;wg-api-football-standings&quot;
        ///    data-host=&quot;v3.football.api-sports.io&quot;
        ///    data-key=&quot;6382ac6ee050e80202c6e4eb4ac42321&quot;
        ///    data-league=&quot;140&quot;
        ///    data-team=&quot;&quot;
        ///    data-season=&quot;2021&quot;
        ///    data-theme=&quot;dark&quot;
        ///    data-show-errors=&quot;true&quot;
        ///    data-show-logos=&quot;true&quot;
        ///    class=&quot;wg_loader&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;script
        ///    type=&quot;module&quot;
        ///    src=&quot;https://widgets.api-sports.io/football/1.1.8/widget.js&quot;&gt;
        ///&lt;/script&gt;
        ///
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string LaLigaStandings {
            get {
                return ResourceManager.GetString("LaLigaStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;div id=&quot;wg-api-football-standings&quot;
        ///    data-host=&quot;v3.football.api-sports.io&quot;
        ///    data-key=&quot;6382ac6ee050e80202c6e4eb4ac42321&quot;
        ///    data-league=&quot;61&quot;
        ///    data-team=&quot;&quot;
        ///    data-season=&quot;2021&quot;
        ///    data-theme=&quot;dark&quot;
        ///    data-show-errors=&quot;true&quot;
        ///    data-show-logos=&quot;true&quot;
        ///    class=&quot;wg_loader&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;script
        ///    type=&quot;module&quot;
        ///    src=&quot;https://widgets.api-sports.io/football/1.1.8/widget.js&quot;&gt;
        ///&lt;/script&gt;
        ///
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string Ligue1Standings {
            get {
                return ResourceManager.GetString("Ligue1Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;div id=&quot;wg-api-football-standings&quot;
        ///    data-host=&quot;v3.football.api-sports.io&quot;
        ///    data-key=&quot;6382ac6ee050e80202c6e4eb4ac42321&quot;
        ///    data-league=&quot;39&quot;
        ///    data-team=&quot;&quot;
        ///    data-season=&quot;2021&quot;
        ///    data-theme=&quot;dark&quot;
        ///    data-show-errors=&quot;true&quot;
        ///    data-show-logos=&quot;true&quot;
        ///    class=&quot;wg_loader&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;script
        ///    type=&quot;module&quot;
        ///    src=&quot;https://widgets.api-sports.io/football/1.1.8/widget.js&quot;&gt;
        ///&lt;/script&gt;
        ///
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string PremStandings {
            get {
                return ResourceManager.GetString("PremStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;div id=&quot;wg-api-football-standings&quot;
        ///    data-host=&quot;v3.football.api-sports.io&quot;
        ///    data-key=&quot;6382ac6ee050e80202c6e4eb4ac42321&quot;
        ///    data-league=&quot;135&quot;
        ///    data-team=&quot;&quot;
        ///    data-season=&quot;2021&quot;
        ///    data-theme=&quot;dark&quot;
        ///    data-show-errors=&quot;true&quot;
        ///    data-show-logos=&quot;true&quot;
        ///    class=&quot;wg_loader&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;script
        ///    type=&quot;module&quot;
        ///    src=&quot;https://widgets.api-sports.io/football/1.1.8/widget.js&quot;&gt;
        ///&lt;/script&gt;
        ///
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string SerieStandings {
            get {
                return ResourceManager.GetString("SerieStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
